#!/bin/sh
set -e

case "$1" in
    configure)
        [ "x${DEVICE}" = "x" ] && DEVICE="$(cat /proc/device-tree/model)"
        case "$DEVICE" in
            "AMLOGIC")
                MODEL=c1
                DEVICE="Hardkernel ODROID C0/C1+"
                ;;
            "ODROID-C2")
                MODEL=c2
                DEVICE="Hardkernel ODROID C2"
                ;;
            "Hardkernel ODROID-N2")
                MODEL=n2
                DEVICE="Hardkernel ODROID N2"
                ;;
            "Hardkernel Odroid XU4")
                MODEL=xu4
                DEVICE="Hardkernel ODROID XU4"
                ;;
            *)
                echo "Unknown board type"
                exit 1
                ;;
        esac

        DIRECTORY="/usr/lib/odroid-config/models/"

        find "$DIRECTORY" -depth ! -path "$DIRECTORY" -type d ! -name "${MODEL}" -exec rm -r {} \;
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


#DEBHELPER#

exit 0
