#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        rm /usr/lib/odroid-config/odroid-config-settings.sh
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


#DEBHELPER#

exit 0
