#!/bin/sh

do_spi()
{
    DEFAULT=--defaultno
    if exist_in "/dev/" "spidev*"; then
        DEFAULT=
    fi

    whiptail --yesno "Would you like the SPI interface to be enabled?" $DEFAULT 20 60
    BUTTON=$?
    if [ $BUTTON -eq 0 ]; then
        if [ -n "$DEFAULT" ]; then
            loadModule spidev
            loadModule spi_gpio
            loadModule spi_bitbang
            whiptail --msgbox "The SPI interface is enabled." 20 60
        fi
    elif [ $BUTTON -eq 1 ]; then
        if [ -z "$DEFAULT" ]; then
            unLoadModule spidev
            unLoadModule spi_gpio
            unLoadModule spi_bitbang
            whiptail --msgbox "The SPI interface is disabled." 20 60
        fi
    fi
}

do_i2c()
{
    DEFAULT=--defaultno
    if exist_in "/dev/" "i2c*"; then
        DEFAULT=
    fi

    whiptail --yesno "Would you like the I2C interface to be enabled?" $DEFAULT 20 60
    BUTTON=$?
    if [ $BUTTON -eq 0 ]; then
        if [ -n "$DEFAULT" ]; then
            loadModule aml_i2c
            whiptail --msgbox "The I2C interface is enabled." 20 60
        fi
    elif [ $BUTTON -eq 1 ]; then
        if [ -z "$DEFAULT" ]; then
            unLoadModule aml_i2c
            whiptail --msgbox "The I2C interface is disabled." 20 60
        fi
    fi
}

do_onewire()
{
    DEFAULT=--defaultno
    if exist_in "/sys/bus/w1/devices/" "w1_bus*"; then
        DEFAULT=
    fi

    whiptail --yesno "Would you like the 1-Wire interface to be enabled?" $DEFAULT 20 60
    BUTTON=$?
    if [ $BUTTON -eq 0 ]; then
        if [ -n "$DEFAULT" ]; then
            loadModule w1-gpio
            loadModule w1-therm
            whiptail --msgbox "The I2C interface is enabled." 20 60
        fi
    elif [ $BUTTON -eq 1 ]; then
        if [ -z "$DEFAULT" ]; then
            unLoadModule w1-gpio
            unLoadModule w1-therm
            whiptail --msgbox "The I2C interface is disabled." 20 60
        fi
    fi
}